// src/main.rs — generated by the harness, not the model.
use std::io::Read;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let name = args.iter().skip(1).find(|a| !a.starts_with('-')).cloned()
        .or_else(|| {
            args.iter().position(|a| a == "--effect")
                .and_then(|i| args.get(i + 1).cloned())
        });
    let name = match name {
        Some(n) => n,
        None => {
            eprintln!("usage: ttfx <effect>   (available: {})",
                      ttfx::effects::effect_names().join(", "));
            std::process::exit(2);
        }
    };
    let mut input = String::new();
    let _ = std::io::stdin().read_to_string(&mut input);
    if input.trim().is_empty() {
        input = "TerminalTextEffects".to_string();
    }
    let effect = match ttfx::effects::get_effect(&name) {
        Some(e) => e,
        None => {
            eprintln!("unknown effect: {}", name);
            std::process::exit(2);
        }
    };
    for frame in effect.frames(&input) {
        println!("{}", frame);
    }
}
